export const ANALYSIS_FILE_NAME = 'analysis_file_name'
export const GET_SEGMENTS = 'get_segments'
export const GET_SECTIONS = 'get_sections'
export const GET_SYMBOLS = 'get_symbols'
export const GET_RELOCATIONS = 'get_relocations'
