export const ANALYSIS_FILE_NAME = 'analysis_file_name'
export const GET_SEGMENTS = 'get_segments'
export const GET_SECTIONS = 'get_sections'
export const GET_SYMBOLS = 'get_symbols'
export const GET_RELOCATIONS = 'get_relocations'
export const GET_TEXT = 'get_text'
export const GET_DATA = 'get_data'
export const GET_RODATA = 'get_rodata'
export const GET_DYNAMIC = 'get_dynamic'
export const GET_DYNSTR = 'get_dynstr'
export const GET_DYNSYM = 'get_dynsym'
export const GET_GOT = 'get_got'
export const GET_PLT = 'get_plt'

